### ISSUE TITLE
Lower minimum Java version

### ISSUE THREAD

**Issue by Marko19907** [Valkryst/VController#3]
Could you perhaps lower the Java version to something lower like the oldest supported JDK for example? I want to use the library for a large repo but can't because we're still on 17.

**Comment by Valkryst** [comment]
For sure. I just lowered it from `21` to `11` and set the latest release version to `2023.10.24`. Let me know if you run into any issues 👍

JitPack can be a little slow when doing the first build of a new release, so don't worry if Maven/Gradle/SBT takes longer than usual

**Comment by Marko19907** [comment]
Thanks a lot! Unfortunately, it's still an issue with JDK 17

```
ControllerExample.java:8:32
java: cannot access com.valkryst.VController.ControllerPoller
  bad class file: /C:/Users/Marko/.m2/repository/com/github/Valkryst/VController/2023.10.24/VController-2023.10.24.jar!/com/valkryst/VController/ControllerPoller.class
    class file has wrong version 65.0, should be 61.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by Valkryst** [comment]
Could you try it with the library version set to `d1f59dec54d88e4bc3cdecfbdbc824bad0268fcd` from `2023.10.24`?

Looks like I forgot to downgrade the `maven-compiler-plugin` version

**Comment by Marko19907** [comment]
That works, thanks a lot! 🥳
